--- # my handlers section
- name: handlers section
  hosts: all
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: install httpd into webservers group
      action: yum name=httpd state=installed

    - name: start httpd service
      action: service name=httpd state=started
