--- # install multiple packages
- name: my loops playbook
  hosts: webservers
  become: yes

  tasks:
    - name: install packages
      yum:
        name: ['git','which','docker','mysql','tree','wget','httpd','java']
        state: installed
