--- #my targets section
- hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  tasks:
    - name: installing httpd software in webservers
      action: yum name=httpd state=installed

