--- # new users name
- name: my playbook new user
  hosts: webservers
  user: ansible
  become: yes
  connection: ssh

  vars: 
   user: sunny

  tasks:
    - name: creating user {{user}} 
      user:
        name: "{{user}}"
